[cross_validation]
n_splits    = 5

[model]
# num_of_layers       = 17

# torch.nn.DataLoader(...)
[dataloader]
batch_size          = 16
num_workers         = 4
prefetch_factor     = 4
pin_memory          = true
persistent_workers  = true

# torch
[optimizer]
lr = 1e-3

# our fit method
[fit]
epochs = 10
